### PR TITLE
PHP Fatal error when uninstalling.

### PR DESCRIPTION
**Pull request by e0ipso**
Due to discovery for disabled modules.

### CODE REVIEW

**Comment by e0ipso** [comment]
@plopesc kindly review, please.

**Comment by e0ipso** [comment]
@plopesc that is only true if we can guarantee that `plug_config` will **never** provide a plugin.

**Comment by plopesc** [comment]
Yep, but in that case, the module would be hacked by someone.
If plug_config maintainers decide that plug_config will provide plugins, we will be forced to change the approach.
Do we want to give support to people who kill kittens?? :p

What do you think?

**Comment by e0ipso** [comment]
Fair enough, I was thinking about the maintainers adding a plugin without remembering this exception.

I'll update the PR when I get a slot.

**Comment by plopesc** [comment]
Sweet. Thank you man

**Pull request merged**
